runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /class1\.html
  static_files: www/class1.html
  upload: www/class1.html

- url: /class2\.html
  static_files: www/class2.html
  upload: www/class2.html
